# This file configures the analyzer, which statically analyzes Dart code to
# check for errors, warnings, and lints.

include: package:flutter_lints/flutter.yaml

# =========================
# Dart / Flutter lints
# =========================
linter:
  rules:
    use_key_in_widget_constructors: false
    always_declare_return_types: true
    always_use_package_imports: true

    close_sinks: true
    cancel_subscriptions: true
    require_trailing_commas: true

    empty_catches: false
    prefer_single_quotes: true
    unnecessary_await_in_return: true
    prefer_final_in_for_each: true
    prefer_final_locals: true
    unnecessary_brace_in_string_interps: false

# =========================
# Analyzer
# =========================
analyzer:
  plugins:
    - custom_lint

  errors:
    unused_element: ignore
    invalid_annotation_target: ignore

  exclude:
    - lib/**.freezed.dart
    - lib/**.g.dart
    - lib/l10n/gen_l10n/**.dart
    - plugins/**

# =========================
# Riverpod lint rules
# =========================
custom_lint:
  rules:
    # ---------- Core ----------
    - missing_provider_scope
    - provider_parameters
    - avoid_build_context_in_providers
    - riverpod_syntax_error
    - functional_ref

    # ---------- Notifier / @riverpod ----------
    - provider_dependencies
    - scoped_providers_should_specify_dependencies
    - notifier_build: false
    - notifier_extends: false
    - protected_notifier_properties
    - avoid_public_notifier_properties

    # ---------- Lifecycle / memory ----------
    - avoid_ref_inside_state_dispose
    - avoid_keep_alive_dependency_inside_auto_dispose

    # ---------- Cleanup ----------
    - unused_provider
